# Setup
title:               Conversations in Quarantine
tagline:             'supporting food & culture, amidst Covid19'
description:         'Supporting local Asian food businesses in the DMV area in a time of economic and health crises'
url:                 http://shirley-zhou.me/shine2020
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shirley Zhou
  url:               https://www.instagram.com/shur.png/
  email:             shirleyzhou

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
